### ISSUE TITLE
In  4.17.1  after cooked exporting-assets  ,  generate script  would return error

### ISSUE THREAD

**Issue by bigbenzhao** [ArcEcho/TestPak#3]
LogPakFile: Display: Loading response file F:\TestPak-master\TestPak\MyProject\Saved\ProjectUtils\paklist.txt
LogPakFile: Display: Added 2 entries to add to pak file.
LogPakFile: Display: Collecting files to add to pak file...
LogPakFile: Display: Collected 2 files in 0.00s.
LogPakFile: Display: Added 2 files, 96374 bytes total, time 0.07s.
LogPakFile: Display: Unreal pak executed in 0.091288 seconds
LogPakFile: Display: Loading response file F:\TestPak-master\TestPak\MyProject\Saved\ProjectUtils\paklist.txt
LogPakFile: Display: Added 2 entries to add to pak file.
LogPakFile: Display: Collecting files to add to pak file...
LogPakFile: Display: Collected 2 files in 0.00s.
LogPakFile: Display: Added 2 files, 710481 bytes total, time 0.05s.
LogPakFile: Display: Unreal pak executed in 0.065429 seconds
LogPakFile: Display: Loading response file F:\TestPak-master\TestPak\MyProject\Saved\ProjectUtils\paklist.txt
LogPakFile: Display: Added 2 entries to add to pak file.
LogPakFile: Display: Collecting files to add to pak file...
LogPakFile: Display: Collected 2 files in 0.00s.
LogPakFile: Display: Added 2 files, 145386 bytes total, time 0.03s.
LogPakFile: Display: Unreal pak executed in 0.052246 seconds
LogPakFile: Display: Loading response file F:\TestPak-master\TestPak\MyProject\Saved\ProjectUtils\paklist.txt
LogPakFile: Display: Added 0 entries to add to pak file.
LogPakFile: Error: No files specified to add to pak file.
LogPakFile: Display: Unreal pak executed in 0.008599 seconds
Traceback (most recent call last):
  File "Source\generate_pak_files.py", line 185, in <module>
    outputPakFilePath = GeneratePak(targetOutputDir, targetProjectCookedGameDir, longPackageName)
  File "Source\generate_pak_files.py", line 90, in GeneratePak
    subprocess.check_call(pakCmd, shell=True)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"D:\Program Files\Epic Games\UE_4.17\Engine\Binaries\Win64\UnrealPak.exe" "F:\TestPak-master\TestPak\MyProject\Saved\ProjectUtils\0e1c49b50dcb795b0a384c5bc58a0b1861d1383a\9798be2b737f22a0b3c469ebb02ff14e60dba292.pak" -create="F:\TestPak-master\TestPak\MyProject\Saved\ProjectUtils\paklist.txt" -encryptionini -platform=Windows -installed -UTF8Output -multiprocess -patchpaddingalign=2048 -abslog="F:\TestPak-master\TestPak\MyProject\Saved\ProjectUtils\Log\9798be2b737f22a0b3c469ebb02ff14e60dba292.log" -projectdir=F:\TestPak-master\TestPak\MyProject -enginedir=D:\Program Files\Epic Games\UE_4.17' returned non-zero exit status 1.

and when UseBatchPakFile= True   It worked  but the relationship is wrong

**Comment by ArcEcho** [comment]
Make sure you have cooked your project,

**Comment by ArcEcho** [comment]
Make sure you have cooked your project,
